<a href="https://colab.research.google.com/github/mattiasvillani/AdvBayesLearnCourse/blob/master/JAXExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JAX toy example

In [1]:
import jax
import jax.numpy as jnp
from jax import grad, hessian, jit
from scipy.optimize import minimize

jax.config.update("jax_enable_x64", True)  # use float64, important for numerics

### Define the function to be minimized

In [2]:
def f(x):
  return jnp.sum(x**2) + (x[0] - 1) * x[1]

### Test drive by computing the function, gradient and Hessian at x = [1,2,3]

In [12]:
# Value, gradient, Hessian
x0 = jnp.array([1.0, 2.0, 3.0])
print("Function value: ", f(x0))
print("Gradient value: ", grad(f)(x0))
print("Hessian value: \n", hessian(f)(x0))

Function value:  14.0
Gradient value:  [4. 4. 6.]
Hessian value: 
 [[2. 1. 0.]
 [1. 2. 0.]
 [0. 0. 2.]]


### Optimize the function using scipy.optimize.minimize


In [5]:
grad_f    = jit(grad(f))
hessian_f = jit(hessian(f))

res = minimize(
  fun=lambda x: float(f(jnp.array(x))),
  x0=[1.0, 2.0, 0.0],
  jac=lambda x: jax.device_get(grad_f(jnp.array(x))),
  method="BFGS",
  options={"gtol": 1e-8}
)

res.x

array([-0.33333333,  0.66666667,  0.        ])